#-------------------------------------------------------------------------------
#
#  How to Think Like a Computer Scientist: Learning with Python  2nd Edition
#
#  Activity: freindslist
#
#  make - creates xhtml version of this activity.
#
#  make clean - removes .xhtml file 
#
#-------------------------------------------------------------------------------

build:
	lore --config template=template.tpl --config ext=".xhtml" index.lore 

clean:
	rm  *.xhtml
